#!/usr/bin/env ruby
# Sets up tarspoon

require 'uri'
require 'pathname'

# Evaluate configuration
def config() eval File.read('/etc/ts.conf') end

# Import GPG public key
def gpg_import(gpgconf) 
  if gpgconf[:key_id] then
    puts "Getting a key with ID #{gpgconf[:key_id]} from pgp.mit.edu"
    `gpg --keyserver pgp.mit.edu --recv-key #{gpgconf[:key_id]} && echo ok || echo ko`[-2, 2] == 'ok'
  else
    puts "Downloading key from #{gpgconf[:url].to_s}"
    filename = Pathname(gpgconf[:url].path).basename.to_s
    `wget -O /tmp/#{filename} #{gpgconf[:url].to_s} &&
     gpg --import /tmp/#{filename} &&
     echo ok || echo ko`[-2, 2] == 'ok'
  end
end

# For each server make a tunnel script
# todo:

# Make socks proxy
# todo:

gpg_import(config()[:key])
